-- insert into tbl_categories
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('https://cdn.galileo.pgsitecore.com/en-us/-/media/Tide/Images/Products/Listing/liquid/New_21July2016/Tide_Free_and_Gentle_liquid_nonHE.png','Category 1', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('https://lh5.ggpht.com/8Cog_N-0uEK0oWbePxekK2-bPuc2nNAz99kQniCQF2_sx_QPOSXVbZgykleDy2pCOjM=w300','Category 2', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('https://seqlegal.com/sites/default/files/free-legal-document-images/cloud.png','Category 3', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('http://cdn.24.co.za/files/Cms/General/d/3076/4fbb842be26d481aa047adab4603fba6.jpg','Category 4', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('https://www.ibaudio.com/Images/BundlePics/free-ride.jpg','Category 5', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('https://nimax-img.de/Produktbilder/normal/55558_2/Tasco-Binoclu-Focus-Free-7x35.jpg','Category 6', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Category 7', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_categories (cat_image_path, cat_name, cat_description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Category 8', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');

-- insert into tbl_products



-- insert into tbl_users
INSERT INTO tbl_users (usr_id, usr_username, usr_password, usr_email, usr_is_active) VALUES (1, 'admin', 'admin', 'admin@yahoo.com', true);
INSERT INTO tbl_users (usr_id, usr_username, usr_password, usr_email, usr_is_active) VALUES (2, 'admin2', 'admin2', 'admin@yahoo.com', true);

-- insert into tbl_traditional_products
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('https://www.businesseventssydney.com.au/media/1351/13-free-wifi-in-the-city.jpg','Product 1', '114 adadeerrff + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('https://www.businesseventssydney.com.au/media/1341/1-festivals-and-events.jpg','Product 2', '114 gggggggggg + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('https://www.businesseventssydney.com.au/media/1343/2-darling-harbour.jpg','Product 3', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('https://www.businesseventssydney.com.au/media/1345/7-coastal-walks.jpg','Product 4', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 5', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 6', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 7', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 8', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 9', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 10', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 11', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 12', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 13', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 14', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 15', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 16', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 17', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 18', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 19', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');
INSERT INTO tbl_traditional_products (image_path, name, description) VALUES ('http://www.cali.ro/330-thickbox_default/sugar-free-gummies-calivita-jeleuri-cu-multivitamine-pentru-copii.jpg','Product 20', '114 characters + - dbhmfbdhsmfhdbfnbbdmbbsdbfmdshfbmsddkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk');